wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: catboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.6
    start_time: 1671123925.232122
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 7
      - 53
      - 55
      3:
      - 23
      4: 3.8.6
      5: 0.13.5
      8:
      - 1
      - 5
