---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-builtin-literals
      - id: check-byte-order-marker
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
  - repo: https://github.com/PyCQA/autoflake
    rev: v1.7.7
    hooks:
      - id: autoflake
        args:
          - "--check"
          - "--ignore-init-module-imports"
          - "--remove-all-unused-imports"
          - "--remove-unused-variables"
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args:
          - "--check-only"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        # yaml requires additional stubs.
        # Similar to: https://stackoverflow.com/a/73603491/5755604
        additional_dependencies: ['types-PyYAML']
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-use-type-annotations
  - repo: https://github.com/PyCQA/doc8
    rev: v1.0.0
    hooks:
      - id: doc8
        name: doc8
        description: This hook runs doc8 for linting docs.
        entry: python -m doc8
        language: python
        files: \.rst$
        require_serial: true
  - repo: https://github.com/psf/black.git
    rev: 22.10.0
    hooks:
      - id: black
        args:
          - "--check"
        language_version: python3
        exclude: ^(tests\/hooks-abort-render\/hooks|docs)
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-absolute-import
          - flake8-black
          - flake8-docstrings
          - flake8-bugbear
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.2.2
    hooks:
      - id: pyupgrade
exclude: "^(references|reports)"
