version: 1
disable_existing_loggers: False
formatters:
  default:
    class: logging.Formatter
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stdout
loggers:
  otc:
    level: INFO
    propagate: yes
root:
  level: NOTSET
  handlers: [console]
  propogate: no
