---
name: Build LaTeX document
on:
  push:
    paths:
      - reports/**
  workflow_dispatch: null
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v5
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          latexmk_shell_escape: true
          root_file: |
            thesis.tex
            summary.tex
          working_directory: reports
          latexmk_use_lualatex: true
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            reports/thesis.pdf
            reports/summary.pdf
      - name: save tmp copy
        run: |
          mkdir ~/tmplatex
          mv reports/thesis.pdf ~/tmplatex/thesis.pdf
      - name: setup target repo
        uses: actions/checkout@v5
        with:
          repository: KarelZe/thesis2video
          ref: main
          token: ${{secrets.API_TOKEN_GITHUB}}
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "action@markusbilz.com"
      - name: Move file and push
        run: |
          mv ~/tmplatex/thesis.pdf ${{github.event.repository.pushed_at}}-thesis.pdf
          git add -A
          git commit -m "Version @ ${{github.event.repository.pushed_at}}"
          git push origin main
