name: Build LaTeX document
on:
  push:
    paths:
    - 'reports/**'
  workflow_dispatch:
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          latexmk_shell_escape: true
          root_file: |
            expose.tex
            thesis.tex
          working_directory: reports
          latexmk_use_lualatex: true
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            reports/expose.pdf
            reports/thesis.pdf
      - name: Rename file and move
        run: mv reports/thesis.pdf output/"${{github.event.repository.updated_at}}"-thesis.pdf
      - name: Push drafts to another repo
        uses: cpina/github-action-push-to-another-repository@ssh-deploy-key
        env:
          SSH_DEPLOY_KEY: ${{secrets.THESIS_2_VIDEO}}
        with:
          source-directory: output/
          destination-github-username: 'KarelZe'
          destination-repository-name: 'thesis2video'
          user-email: action@markusbilz.com
          commit-message: pushed from $GITHUB_REF
          target-branch: main
