name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create application default credentials  
      run: |
          echo "$APP_CRED" >> $HOME/.config/gcloud/application_default_credentials.json
      shell: bash
      env:
        APP_CRED: ${{secrets.APPLICATION_DEFAULT_CREDENTIALS}}
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Test with pytest
      run: |
        pip install pytest
        pip install pytest-cov
        pytest --cov=src tests/ --doctest-modules --junitxml=junit/test-results.xml --cov-report=xml --cov-report=html